version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=todolist
      - POSTGRES_DB=todo_db
    ports:
      - "5432:5432"
    volumes:
      - /temp
